name: Notify Discord on PR

on:
  pull_request:
    types: [opened]

jobs:
  discord_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send PR notification to Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
        run: |
          curl -H "Content-Type: application/json" \
            -X POST \
            -d "{\"content\": \"📣 **New Pull Request Created!**\n🔗 [${PR_TITLE}](${PR_URL}) by **${PR_AUTHOR}**\"}" \
            $DISCORD_WEBHOOK_URL
